# Pandas

## Series

In [1]:
import pandas as pd
import numpy as np

In [2]:
students = pd.Series(['Robert', 'Charly', 'George', 'Leo'])
students

0    Robert
1    Charly
2    George
3       Leo
dtype: object

In [4]:
students = pd.Series(['Robert', 'Charly', 'George', 'Leo'], index=[1, 30, 10, 7])
students

1     Robert
30    Charly
10    George
7        Leo
dtype: object

In [5]:
dict = {1:'Robert', 7:'Charly', 10:'George', 30:'Leo'}

In [7]:
students = pd.Series(dict)
students

1     Robert
7     Charly
10    George
30       Leo
dtype: object

In [9]:
my_array = np.array([10, 20, 30, 40, 50])
my_series = pd.Series(my_array, index = ["num1", "num2", "num3", "num4", "num5"])
my_series

num1    10
num2    20
num3    30
num4    40
num5    50
dtype: int64

## Acceso a series

In [20]:
my_series[2:3]

num3    30
dtype: int64

In [21]:
my_series[2]

/var/folders/bp/znc8s05d0pj5wgzwww5sdk3w0000gp/T/ipykernel_8068/1470048285.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  my_series[2]

np.int64(30)

In [15]:
my_series['num3']

np.int64(30)

In [16]:
my_series[0:3]

num1    10
num2    20
num3    30
dtype: int64

In [23]:
my_series = pd.Series([5, 8, 2, 11, 9])

In [24]:
np.min(my_series)

np.int64(2)

In [25]:
np.max(my_series)

np.int64(11)

In [26]:
my_series.mean()

np.float64(7.0)

In [27]:
my_series.median()

np.float64(8.0)

In [31]:
type(my_series)

pandas.core.series.Series

In [32]:
my_series.dtype

dtype('int64')

## DataFrames

In [33]:
scores = [['Mathematics', 85], ['English', 91], ['History', 95]]

In [34]:
my_df = pd.DataFrame(scores, columns=['Subject', 'Score'])
my_df

       Subject  Score
0  Mathematics     85
1      English     91
2      History     95

In [35]:
scores = {
    'Subject':["Mathematics", "History", "English", "Science", "Arts"],
    'Score':[98, 75, 68, 82, 99]
}

In [36]:
my_df = pd.DataFrame(scores)
my_df

       Subject  Score
0  Mathematics     98
1      History     75
2      English     68
3      Science     82
4         Arts     99

## Operaciones básicas `head` y `tail`

In [38]:
my_df.head(2)

       Subject  Score
0  Mathematics     98
1      History     75

In [39]:
my_df.tail(3)

   Subject  Score
2  English     68
3  Science     82
4     Arts     99

## Resumen de un dataframe

In [40]:
my_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Subject  5 non-null      object
 1   Score    5 non-null      int64
dtypes: int64(1), object(1)
memory usage: 212.0+ bytes

## Estadísiticos básicos

In [41]:
my_df.describe()

           Score
count   5.000000
mean   84.400000
std    13.794927
min    68.000000
25%    75.000000
50%    82.000000
75%    98.000000
max    99.000000

## Importar datos a Pandas desde CSV

In [42]:
iris_data = pd.read_csv('data/iris_data.csv')
iris_data.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [44]:
headers = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']
iris_data = pd.read_csv('data/iris_data_no_headers.csv', names=headers)
iris_data.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa